package gw

import (
	"errors"
	"unsafe"

	"github.com/mkch/gg"
	"github.com/mkch/gw/app"
	"github.com/mkch/gw/events"
	internal_app "github.com/mkch/gw/internal/app"
	"github.com/mkch/gw/internal/appmsg"
	"github.com/mkch/gw/menu"
	"github.com/mkch/gw/metrics"
	"github.com/mkch/gw/win32"
	"github.com/mkch/gw/win32/win32util"
	"golang.org/x/sys/windows"
)

var CW_USEDEFAULT = metrics.Px(win32.CW_USEDEFAULT)

// windowProp is the window property to associate a [BaseWindow] instance with an HWND.
var windowProp = win32util.NewWindowProp[BaseWindow]("github.com/mkch/gw#WindowProp")

// LookupWindow returns the [BaseWindow] instance associated with hwnd by calling [Init] or [Attach].
// It returns nil if not found.
func LookupWindow(hwnd win32.HWND) BaseWindow {
	p := windowProp.Get(hwnd)
	if p != nil {
		return *p
	}
	return nil
}

type msgListenerMap map[MsgListenerKey]func(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM)

// MsgListenerKey represents a message listener added by [Window1.AddMsgListener].
type MsgListenerKey struct {
	m      *msgListenerMap
	unique *uintptr // generated by new(uintptr)
}

// Remove removes the listener.
func (k MsgListenerKey) Remove() {
	delete(*k.m, k)
}

// BaseWindow is the base interface for all windows and controls created and attached in this package.
type BaseWindow interface {
	// App returns the app that this window belongs to.
	App() *app.BaseApp
	// CreateHandle is called to create the window handle in [Init].
	CreateHandle() win32.HWND
	// HWND returns the HWND of this window. It panics if the window is uninitialized.
	HWND() win32.HWND
	// Valid returns whether the window is ready to operate, specifically, whether
	// HWND method is safe to call without panic.
	Valid() bool
	// Parent returns the parent window of this window, or nil if it has no parent.
	Parent() BaseWindow
	// Destroy destroys the window.
	Destroy() error
	// TrackPopupMenu tracks a popup menu.
	// If spec is nil, default flag, empty exclude RECT and GetCursorPos() are used.
	TrackPopupMenu(menu *menu.Menu, spec *PopupMenuSpec) error
	// Show shows or hides the window.
	Show(cmd win32.SHOW_WINDOW_CMD)
	// SetText sets the text of the window.
	SetText(text string) error
	// Test returns the text of the window.
	Text() (string, error)
	// DPI returns the DPI of the window.
	DPI() (win32.UINT, error)
	GetClientRect() (*win32.RECT, error)
	GetWindowRect() (*win32.RECT, error)
	InvalidateRect(rect *win32.RECT, eraseBk bool) error
	// AddMsgListener adds a listener that is called when the message is received in the window procedure.
	// To remove the listener, call Remove() of the returned MsgListenerKey.
	AddMsgListener(message win32.UINT,
		listener func(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM)) MsgListenerKey
	// Value returns the value associated with this window for key, or nil
	// if no value is associated with key.
	// See Context.Value() in context package for the concept and usage of associated value.
	Value(key any) any
	// Value sets the value associated with this window for key.
	// Setting A nil value deletes the value associated with key if any.
	// See Context.Value() in context package for the concept and usage of associated value.
	SetValue(key, value any)

	SetOnLButtonUpListener(func(event events.MouseClickEvent))
	SetOnLButtonDownListener(func(event events.MouseClickEvent))
	SetOnRButtonUpListener(func(event events.MouseClickEvent))
	SetOnRButtonDownListener(func(event events.MouseClickEvent))
	SetOnLButtonDoubleClickListener(func(event events.MouseClickEvent))
	SetOnSizeListener(func(event events.SizeEvent))
	SetOnDestroyListener(func())

	// WndProc is called when a message is received in the window procedure.
	// The default implementation calls the native window procedure.
	WndProc(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM) win32.LRESULT
	// OnInit is called when the window is created and fully initialized.
	OnInit()
	// OnDestroy is called when the window is being destroyed, when WM_DESTROY message is received.
	// The window and all its children are still valid when this method is called.
	// The default implementation calls the destroy listener if it is set, and then calls the
	// native window procedure to process the message.
	OnDestroy()
	// OnPaint is called when the window needs to be repainted, when WM_PAINT message is received.
	// The default implementation calls the native window procedure to process the message.
	OnPaint()
	// OnKeyDown is called when WM_KEYDOWN message is received.
	// The default implementation calls the native window procedure to process the message.
	OnKeyDown(event *events.KeyEvent)
	// OnKeyUp is called when WM_KEYUP message is received.
	// The default implementation calls the native window procedure to process the message.
	OnKeyUp(event *events.KeyEvent)
	// OnSysKeyDown is called when WM_SYSKEYDOWN message is received.
	// The default implementation calls the native window procedure to process the message.
	OnSysKeyDown(event *events.KeyEvent)
	// OnSysKeyUp is called when WM_SYSKEYUP message is received.
	// The default implementation calls the native window procedure to process the message.
	OnSysKeyUp(event *events.KeyEvent)
	// OnLButtonDown is called when WM_LBUTTONDOWN message is received.
	// The default implementation calls the left button down listener if it is set, and then calls the
	// native window procedure to process the message.
	OnLButtonDown(event *events.MouseClickEvent)
	// OnLButtonUp is called when WM_LBUTTONUP message is received.
	// The default implementation calls the left button up listener if it is set, and then calls the
	// native window procedure to process the message.
	OnLButtonUp(event *events.MouseClickEvent)
	// OnRButtonDown is called when WM_RBUTTONDOWN message is received.
	// The default implementation calls the right button down listener if it is set, and then calls the
	// native window procedure to process the message.
	OnRButtonDown(event *events.MouseClickEvent)
	// OnRButtonUp is called when WM_RBUTTONUP message is received.
	// The default implementation calls the right button up listener if it is set, and then calls the
	// native window procedure to process the message.
	OnRButtonUp(event *events.MouseClickEvent)
	// OnLButtonDoubleClick is called when WM_LBUTTONDBLCLK message is received.
	// The default implementation calls the left button double click listener if it is set, and then calls the
	// native window procedure to process the message.
	OnLButtonDoubleClick(event *events.MouseClickEvent)
	// OnSize is called when WM_SIZE message is received.
	// The default implementation calls the size changed listener if it is set, and then calls the
	// native window procedure to process the message.
	OnSize(event *events.SizeEvent)

	setHWND(hwnd win32.HWND)
	setOldWndProc(oldWndProc uintptr)
}

// Ensure [*BaseWindowImpl] implements [BaseWindow].
// Should have no runtime overhead.
var _ BaseWindow = (*BaseWindowImpl)(nil)

// BaseWindowImpl is a helper implementation of [BaseWindow].
// It can be embedded in concrete window types to implement [BaseWindow].
type BaseWindowImpl struct {
	lButtonUpListener          func(event events.MouseClickEvent)
	lButtonDownListener        func(event events.MouseClickEvent)
	rButtonUpListener          func(event events.MouseClickEvent)
	rButtonDownListener        func(event events.MouseClickEvent)
	lButtonDoubleClickListener func(event events.MouseClickEvent)
	sizeChangedListener        func(event events.SizeEvent)
	destroyListener            func()
	msgListeners               map[win32.UINT]msgListenerMap
	values                     map[any]any
	hwnd                       win32.HWND
	oldWndProc                 uintptr // The original window procedure before attaching.
}

func (w *BaseWindowImpl) CreateHandle() win32.HWND {
	panic("CreateHandle must be implemented by concrete window type")
}

func (w *BaseWindowImpl) Parent() BaseWindow {
	p, err := win32.GetParent(w.hwnd)
	if err != nil || p == 0 {
		return nil
	}
	return LookupWindow(p)
}

func (w *BaseWindowImpl) setHWND(hwnd win32.HWND) {
	w.hwnd = hwnd
}

func (w *BaseWindowImpl) setOldWndProc(oldWndProc uintptr) {
	w.oldWndProc = oldWndProc
}

func (w *BaseWindowImpl) App() *app.BaseApp {
	return internal_app.ThreadLocalApp()
}

func (w *BaseWindowImpl) Valid() bool {
	return w.hwnd != 0
}

func (w *BaseWindowImpl) HWND() win32.HWND {
	if !w.Valid() {
		panic("window is uninitialized")
	}
	return w.hwnd
}

func (w *BaseWindowImpl) SetOnLButtonUpListener(listener func(event events.MouseClickEvent)) {
	w.lButtonUpListener = listener
}

func (w *BaseWindowImpl) callOnLButtonUpListener(event events.MouseClickEvent) {
	if w.lButtonUpListener != nil {
		w.lButtonUpListener(event)
	}
}

func (w *BaseWindowImpl) SetOnLButtonDownListener(listener func(event events.MouseClickEvent)) {
	w.lButtonDownListener = listener
}

func (w *BaseWindowImpl) callOnLButtonDownListener(event events.MouseClickEvent) {
	if w.lButtonDownListener != nil {
		w.lButtonDownListener(event)
	}
}

func (w *BaseWindowImpl) SetOnRButtonUpListener(listener func(event events.MouseClickEvent)) {
	w.rButtonUpListener = listener
}

func (w *BaseWindowImpl) callOnRButtonUpListener(event events.MouseClickEvent) {
	if w.rButtonUpListener != nil {
		w.rButtonUpListener(event)
	}
}

func (w *BaseWindowImpl) SetOnRButtonDownListener(listener func(event events.MouseClickEvent)) {
	w.rButtonDownListener = listener
}

func (w *BaseWindowImpl) callOnRButtonDownListener(event events.MouseClickEvent) {
	if w.rButtonDownListener != nil {
		w.rButtonDownListener(event)
	}
}

func (w *BaseWindowImpl) SetOnLButtonDoubleClickListener(listener func(event events.MouseClickEvent)) {
	w.lButtonDoubleClickListener = listener
}

func (w *BaseWindowImpl) callOnLButtonDoubleClickListener(event events.MouseClickEvent) {
	if w.lButtonDoubleClickListener != nil {
		w.lButtonDoubleClickListener(event)
	}
}

func (w *BaseWindowImpl) SetOnDestroyListener(listener func()) {
	w.destroyListener = listener
}

func (w *BaseWindowImpl) SetOnSizeListener(listener func(event events.SizeEvent)) {
	w.sizeChangedListener = listener
}

func (w *BaseWindowImpl) callOnSizeChangedListener(event events.SizeEvent) {
	if w.sizeChangedListener != nil {
		w.sizeChangedListener(event)
	}
}

func (w *BaseWindowImpl) callOnDestroyListener() {
	if w.destroyListener != nil {
		w.destroyListener()
	}
}

func (w *BaseWindowImpl) OnInit() { /* NOP */ }

func (w *BaseWindowImpl) OnDestroy() {
	w.callOnDestroyListener()
	w.defWndProc(w.hwnd, win32.WM_DESTROY, 0, 0)
}

func (w *BaseWindowImpl) OnPaint() {
	// For performance, do not call h.HWND()
	w.defWndProc(w.hwnd, win32.WM_PAINT, 0, 0)
}

func (w *BaseWindowImpl) Destroy() error {
	return win32.DestroyWindow(w.HWND())
}

func (w *BaseWindowImpl) WndProc(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM) win32.LRESULT {
	if w.msgListeners != nil {
		if listeners := w.msgListeners[message]; listeners != nil {
			for _, l := range listeners {
				l(hwnd, message, wParam, lParam)
			}
		}
	}
	switch message {
	case win32.WM_NCDESTROY:
		windowProp.Set(hwnd, nil)
		w.hwnd = 0
	case win32.WM_DESTROY:
		LookupWindow(hwnd).OnDestroy()
	case win32.WM_CTLCOLORSTATIC:
		if ret, err := win32.SendMessageW(win32.HWND(lParam), appmsg.REFLECT_CTLCOLORSTATIC, wParam, lParam); err == nil && ret != 0 {
			return ret
		}
	case win32.WM_LBUTTONUP:
		LookupWindow(hwnd).OnLButtonUp(new(events.NewMouseClickEvent(wParam, lParam)))
	case win32.WM_LBUTTONDOWN:
		LookupWindow(hwnd).OnLButtonDown(new(events.NewMouseClickEvent(wParam, lParam)))
	case win32.WM_RBUTTONUP:
		LookupWindow(hwnd).OnRButtonUp(new(events.NewMouseClickEvent(wParam, lParam)))
	case win32.WM_RBUTTONDOWN:
		LookupWindow(hwnd).OnRButtonDown(new(events.NewMouseClickEvent(wParam, lParam)))
	case win32.WM_LBUTTONDBLCLK:
		LookupWindow(hwnd).OnLButtonDoubleClick(new(events.NewMouseClickEvent(wParam, lParam)))
	case win32.WM_KEYDOWN:
		LookupWindow(hwnd).OnKeyDown(new(events.NewKeyEvent(wParam, lParam)))
		return 0
	case win32.WM_SYSKEYDOWN:
		LookupWindow(hwnd).OnSysKeyDown(new(events.NewKeyEvent(wParam, lParam)))
		return 0
	case win32.WM_KEYUP:
		LookupWindow(hwnd).OnKeyUp(new(events.NewKeyEvent(wParam, lParam)))
		return 0
	case win32.WM_SYSKEYUP:
		LookupWindow(hwnd).OnSysKeyUp(new(events.NewKeyEvent(wParam, lParam)))
		return 0
	case win32.WM_PAINT:
		LookupWindow(hwnd).OnPaint()
		return 0 // Not calling default.
	case win32.WM_SIZE:
		LookupWindow(hwnd).OnSize(new(events.NewSizeEvent(wParam, lParam)))
	case win32.WM_DPICHANGED:
		// For top level windows.
		suggested := (*win32.RECT)(unsafe.Pointer(uintptr(unsafe.Add(nil, lParam))))
		win32.SetWindowPos(hwnd, 0,
			win32.INT(suggested.Left), win32.INT(suggested.Top), win32.INT(suggested.Width()), win32.INT(suggested.Height()),
			win32.SWP_NOZORDER|win32.SWP_NOACTIVATE)
	}
	return w.defWndProc(hwnd, message, wParam, lParam)
}

func (w *BaseWindowImpl) defWndProc(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM) win32.LRESULT {
	return win32.CallWindowProcW(w.oldWndProc, hwnd, message, wParam, lParam)
}

// wndProc is the native window procedure for all windows created or attached by this package.
var wndProc = windows.NewCallback(func(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM) (result win32.LRESULT) {
	result = LookupWindow(hwnd).WndProc(hwnd, message, wParam, lParam)
	internal_app.CallMsgRetListeners(internal_app.ThreadLocalApp(), hwnd, message, wParam, lParam, result)
	return
})

func (w *BaseWindowImpl) OnKeyDown(event *events.KeyEvent) {
	w.defWndProc(w.hwnd, win32.WM_KEYDOWN, event.VKCode, win32.LPARAM(event.State))
}

func (w *BaseWindowImpl) OnSysKeyDown(event *events.KeyEvent) {
	w.defWndProc(w.hwnd, win32.WM_SYSKEYDOWN, event.VKCode, win32.LPARAM(event.State))
}

func (w *BaseWindowImpl) OnKeyUp(event *events.KeyEvent) {
	w.defWndProc(w.hwnd, win32.WM_KEYUP, event.VKCode, win32.LPARAM(event.State))
}

func (w *BaseWindowImpl) OnSysKeyUp(event *events.KeyEvent) {
	w.defWndProc(w.hwnd, win32.WM_SYSKEYUP, event.VKCode, win32.LPARAM(event.State))
}

func (w *BaseWindowImpl) OnLButtonDown(event *events.MouseClickEvent) {
	w.callOnLButtonDownListener(*event)
	w.defWndProc(w.hwnd, win32.WM_LBUTTONDOWN, win32.WPARAM(event.Opt), win32.LPARAM(event.Pt))
}

func (w *BaseWindowImpl) OnLButtonUp(event *events.MouseClickEvent) {
	w.callOnLButtonUpListener(*event)
	w.defWndProc(w.hwnd, win32.WM_LBUTTONUP, win32.WPARAM(event.Opt), win32.LPARAM(event.Pt))
}

func (w *BaseWindowImpl) OnRButtonDown(event *events.MouseClickEvent) {
	w.callOnRButtonDownListener(*event)
	w.defWndProc(w.hwnd, win32.WM_RBUTTONDOWN, win32.WPARAM(event.Opt), win32.LPARAM(event.Pt))
}

func (w *BaseWindowImpl) OnRButtonUp(event *events.MouseClickEvent) {
	w.callOnRButtonUpListener(*event)
	w.defWndProc(w.hwnd, win32.WM_RBUTTONUP, win32.WPARAM(event.Opt), win32.LPARAM(event.Pt))
}

func (w *BaseWindowImpl) OnLButtonDoubleClick(event *events.MouseClickEvent) {
	w.callOnLButtonDoubleClickListener(*event)
	w.defWndProc(w.hwnd, win32.WM_LBUTTONDBLCLK, win32.WPARAM(event.Opt), win32.LPARAM(event.Pt))
}

func (w *BaseWindowImpl) OnSize(event *events.SizeEvent) {
	w.callOnSizeChangedListener(*event)
	w.defWndProc(w.hwnd, win32.WM_SIZE, win32.WPARAM(event.Type), win32.LPARAM(event.Size))
}

type PopupMenuSpec struct {
	Flags   win32.TRACK_POPUP_MENU_FLAG
	X, Y    win32.LONG // Screen coordinates.
	Exclude *win32.RECT
}

// TrackPopupMenu tracks a popup menu.
// If spec is nil, default flag, empty exclude RECT and GetCursorPos() are used.
func (w *BaseWindowImpl) TrackPopupMenu(menu *menu.Menu, spec *PopupMenuSpec) error {
	var flags win32.TRACK_POPUP_MENU_FLAG
	var pt = &win32.POINT{}
	var params *win32.TPMPARAMS

	if spec != nil {
		// Notify message is needed.
		if spec.Flags&win32.TPM_NONOTIFY != 0 {
			return errors.New("invalid param: TPM_NONOTIFY is not allowed")
		}
		flags = spec.Flags
		pt.X = win32.LONG(spec.X)
		pt.Y = win32.LONG(spec.Y)
		if spec.Exclude != nil {
			params = &win32.TPMPARAMS{
				Size:    win32.UINT(unsafe.Sizeof(win32.TPMPARAMS{})),
				Exclude: *spec.Exclude,
			}
		}
	} else {
		var err error
		pt, err = win32.GetCursorPos()
		if err != nil {
			return err
		}
		flags = gg.If(win32.GetSystemMetrics(win32.SM_MENUDROPALIGNMENT) != 0, win32.TPM_RIGHTALIGN, win32.TPM_LEFTALIGN)
	}

	// In case the keyboard layout is changed since the menu is created.
	menu.OnKeyboardLayoutChange(win32.GetKeyboardLayout(0))

	// TPM_RIGHTBUTTON makes right clicking select the menu item.
	// If not set, right clicking(releasing right mouse button) of a menu item will post a WM_RBUTTONUP message to the window.
	// If win32.TrackPopupMenuEx is called in a WM_RBUTTONUP handler, the extra WM_RBUTTONUP message will cause a recursive call
	// to win32.TrackPopupMenuEx which results an error of "1446 Popup menu already active".
	flags |= win32.TPM_RIGHTBUTTON
	_, err := win32.TrackPopupMenuEx(menu.HMENU(), flags, win32.INT(pt.X), win32.INT(pt.Y), w.HWND(), params)
	return err
}

func (w *BaseWindowImpl) Show(cmd win32.SHOW_WINDOW_CMD) {
	win32.ShowWindow(w.HWND(), cmd)
}

func (w *BaseWindowImpl) SetText(text string) error {
	return win32util.SetWindowText(w.HWND(), text)
}

func (w *BaseWindowImpl) Text() (string, error) {
	return win32util.GetWindowText(w.HWND())
}

func (w *BaseWindowImpl) DPI() (win32.UINT, error) {
	return win32.GetDpiForWindow(w.HWND())
}

func (w *BaseWindowImpl) GetClientRect() (*win32.RECT, error) {
	var rect win32.RECT
	if err := win32.GetClientRect(w.HWND(), &rect); err != nil {
		return nil, err
	}
	return &rect, nil
}

func (w *BaseWindowImpl) GetWindowRect() (*win32.RECT, error) {
	var rect win32.RECT
	if err := win32.GetWindowRect(w.HWND(), &rect); err != nil {
		return nil, err
	}
	return &rect, nil
}

func (w *BaseWindowImpl) InvalidateRect(rect *win32.RECT, eraseBk bool) error {
	return win32.InvalidateRect(w.HWND(), rect, eraseBk)
}

func (w *BaseWindowImpl) AddMsgListener(message win32.UINT,
	listener func(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM)) MsgListenerKey {
	if listener == nil {
		panic("nil listener")
	}
	if w.msgListeners == nil {
		w.msgListeners = make(map[win32.UINT]msgListenerMap)
	}

	listeners := w.msgListeners[message]
	if listeners == nil {
		listeners = make(msgListenerMap)
		w.msgListeners[message] = listeners
	}
	key := MsgListenerKey{&listeners, new(uintptr)}
	listeners[key] = listener
	return key
}

func (w *BaseWindowImpl) Value(key any) any {
	if w.values == nil {
		return nil
	}
	return w.values[key]
}

func (w *BaseWindowImpl) SetValue(key, value any) {
	if value == nil {
		delete(w.values, key)
		return
	}
	if w.values == nil {
		w.values = make(map[any]any)
	}
	w.values[key] = value
}

// wiErrAlreadyAttached is returned by Attach if the HWND or *WindowBase
// is already attached.
var ErrAlreadyAttached = errors.New("window is already attached")

// Attach attaches an existing window represented by hwnd to a [BaseWindow] instance.
func Attach(hwnd win32.HWND, window BaseWindow) error {
	if LookupWindow(hwnd) != nil {
		return ErrAlreadyAttached
	}
	if proc, err := win32.GetWindowLongPtrW(hwnd, win32.GWLP_WNDPROC); err != nil {
		return err
	} else if proc == win32.LONG_PTR(wndProc) {
		return ErrAlreadyAttached
	}

	oldProc, err := win32.SetWindowLongPtrW(hwnd, win32.GWLP_WNDPROC, win32.LONG_PTR(wndProc))
	if err != nil {
		return err
	}
	windowProp.Set(hwnd, &window)
	window.setHWND(hwnd)
	window.setOldWndProc(uintptr(oldProc))
	return nil
}

// Init creates and initializes the window.
// The return value is the same as the window parameter.
// It panics if the window is already initialized or if creating or initializing the window fails.
// Only [BaseWindow] instances initialized by this function can be retrieved by [LookupWindow].
// One can wrap an uninitialized [BaseWindow] instance to crate a new window type, and then call this
// function to initialize the instance of the new type. See Wrapper example for details.
func Init[T BaseWindow](window T) T {
	if window.Valid() {
		panic("window is already initialized")
	}
	if err := Attach(window.CreateHandle(), window); err != nil {
		panic(err)
	}
	window.OnInit()
	return window
}
