package gw

import (
	"errors"
	"unsafe"

	"github.com/mkch/gg"
	"github.com/mkch/gw/app"
	internal_app "github.com/mkch/gw/internal/app"
	"github.com/mkch/gw/internal/appmsg"
	"github.com/mkch/gw/menu"
	"github.com/mkch/gw/metrics"
	"github.com/mkch/gw/win32"
	"github.com/mkch/gw/win32/win32util"
	"golang.org/x/sys/windows"
)

var CW_USEDEFAULT = metrics.Px(win32.CW_USEDEFAULT)

// windowProp is the window property to associate a BaseWindow instance with an HWND.
var windowProp = win32util.NewWindowProp[BaseWindow]("github.com/mkch/gw#WindowProp")

// LookupWindow returns the [BaseWindow] instance associated with hwnd, previously created by [Init].
// It returns nil if not found.
func LookupWindow(hwnd win32.HWND) BaseWindow {
	p := windowProp.Get(hwnd)
	if p != nil {
		return *p
	}
	return nil
}

type msgListenerMap map[MsgListenerKey]func(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM)

// MsgListenerKey represents a message listener added by [BaseWindow.AddMsgListener].
type MsgListenerKey struct {
	m      *msgListenerMap
	unique *uintptr // generated by new(uintptr)
}

// Remove removes the listener.
func (k MsgListenerKey) Remove() {
	delete(*k.m, k)
}

// WindowParent represents the parent of a window when creating a window.
// It is implemented by [BaseWindow] and [RawParent].
type WindowParent interface {
	HWND() win32.HWND
}

// RawParent is a simple implementation of WindowParent for raw HWND.
type RawParent win32.HWND

func (p RawParent) HWND() win32.HWND {
	return win32.HWND(p)
}

// BaseWindow is the base interface for all windows and controls in this package.
type BaseWindow interface {
	// App returns the app that this window belongs to.
	App() *app.BaseApp
	// HWND returns the HWND of this window. It panics if the window is uninitialized.
	HWND() win32.HWND
	// Valid returns whether the window is ready to operate, specifically, whether
	// HWND method is safe to call without panic.
	Valid() bool
	// Parent returns the parent window of this window, or nil if it has no parent.
	Parent() BaseWindow
	// CreateHandle is called to create the window handle in [Init].
	CreateHandle() win32.HWND
	// WndProc is the window procedure for this window.
	// Concrete window types can rewrite this method to handle messages.
	WndProc(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM) win32.LRESULT
	// OnInit is called when the window is created and fully initialized.
	OnInit()
	// OnDestroy is called when the window is being destroyed, when WM_DESTROY message is received.
	// The window and all its children are still valid when this method is called.
	OnDestroy()
	// OnPaint is called when the window needs to be repainted, when WM_PAINT message is received.
	OnPaint()
	// Destroy destroys the window.
	Destroy() error
	// TrackPopupMenu tracks a popup menu.
	// If spec is nil, default flag, empty exclude RECT and GetCursorPos() are used.
	TrackPopupMenu(menu *menu.Menu, spec *PopupMenuSpec) error
	// Show shows or hides the window.
	Show(cmd win32.SHOW_WINDOW_CMD)
	// SetText sets the text of the window.
	SetText(text string) error
	// Test returns the text of the window.
	Text() (string, error)
	// DPI returns the DPI of the window.
	DPI() (win32.UINT, error)
	GetClientRect() (*win32.RECT, error)
	GetWindowRect() (*win32.RECT, error)
	InvalidateRect(rect *win32.RECT, eraseBk bool) error
	// AddMsgListener adds a listener that is called when the message is received in the window procedure.
	// To remove the listener, call Remove() of the returned MsgListenerKey.
	AddMsgListener(message win32.UINT,
		listener func(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM)) MsgListenerKey
	// Value returns the value associated with this window for key, or nil
	// if no value is associated with key.
	// See Context.Value() in context package for the concept and usage of associated value.
	Value(key any) any
	// Value sets the value associated with this window for key.
	// Setting A nil value deletes the value associated with key if any.
	// See Context.Value() in context package for the concept and usage of associated value.
	SetValue(key, value any)

	SetOnLButtonUpListener(func(opt MouseClickOpt, x int, y int))
	SetOnLButtonDownListener(func(opt MouseClickOpt, x int, y int))
	SetOnRButtonUpListener(func(opt MouseClickOpt, x int, y int))
	SetOnRButtonDownListener(func(opt MouseClickOpt, x int, y int))
	SetOnDestroyListener(func())

	setHWND(hwnd win32.HWND)
	setOldWndProc(oldWndProc uintptr)
	initialized() bool
}

// BaseWindowImpl is a helper implementation of [BaseWindow] without WndProc and CreateHandle method.
// It can be embedded in concrete window types to implement BaseWindow.
type BaseWindowImpl struct {
	lButtonUpListener   func(opt MouseClickOpt, x int, y int)
	lButtonDownListener func(opt MouseClickOpt, x int, y int)
	rButtonUpListener   func(opt MouseClickOpt, x int, y int)
	rButtonDownListener func(opt MouseClickOpt, x int, y int)
	destroyListener     func()
	msgListeners        map[win32.UINT]msgListenerMap
	values              map[any]any
	hwnd                win32.HWND
	oldWndProc          uintptr // The original window procedure before attaching.
}

func (w *BaseWindowImpl) Parent() BaseWindow {
	p, err := win32.GetParent(w.hwnd)
	if err != nil || p == 0 {
		return nil
	}
	return LookupWindow(p)
}

func (w *BaseWindowImpl) setHWND(hwnd win32.HWND) {
	w.hwnd = hwnd
}

func (w *BaseWindowImpl) setOldWndProc(oldWndProc uintptr) {
	w.oldWndProc = oldWndProc
}

func (w *BaseWindowImpl) initialized() bool {
	return w.hwnd != 0
}

func (w *BaseWindowImpl) App() *app.BaseApp {
	return internal_app.ThreadLocalApp()
}

func (w *BaseWindowImpl) Valid() bool {
	return w.hwnd != 0
}

func (w *BaseWindowImpl) HWND() win32.HWND {
	if !w.Valid() {
		panic("window is uninitialized")
	}
	return w.hwnd
}

func (w *BaseWindowImpl) SetOnLButtonUpListener(listener func(opt MouseClickOpt, x int, y int)) {
	w.lButtonUpListener = listener
}

func (w *BaseWindowImpl) callOnLButtonUpListener(opt MouseClickOpt, x int, y int) {
	if w.lButtonUpListener != nil {
		w.lButtonUpListener(opt, x, y)
	}
}

func (w *BaseWindowImpl) SetOnLButtonDownListener(listener func(opt MouseClickOpt, x int, y int)) {
	w.lButtonDownListener = listener
}

func (w *BaseWindowImpl) callOnLButtonDownListener(opt MouseClickOpt, x int, y int) {
	if w.lButtonDownListener != nil {
		w.lButtonDownListener(opt, x, y)
	}
}

func (w *BaseWindowImpl) SetOnRButtonUpListener(listener func(opt MouseClickOpt, x int, y int)) {
	w.rButtonUpListener = listener
}

func (w *BaseWindowImpl) callOnRButtonUpListener(opt MouseClickOpt, x int, y int) {
	if w.rButtonUpListener != nil {
		w.rButtonUpListener(opt, x, y)
	}
}

func (w *BaseWindowImpl) SetOnRButtonDownListener(listener func(opt MouseClickOpt, x int, y int)) {
	w.rButtonDownListener = listener
}

func (w *BaseWindowImpl) callOnRButtonDownListener(opt MouseClickOpt, x int, y int) {
	if w.rButtonDownListener != nil {
		w.rButtonDownListener(opt, x, y)
	}
}

func (w *BaseWindowImpl) SetOnDestroyListener(listener func()) {
	w.destroyListener = listener
}

func (w *BaseWindowImpl) callOnDestroyListener() {
	if w.destroyListener != nil {
		w.destroyListener()
	}
}

func (w *BaseWindowImpl) OnInit() { /* NOP */ }

func (w *BaseWindowImpl) OnDestroy() {
	w.callOnDestroyListener()
	w.defWndProc(w.hwnd, win32.WM_DESTROY, 0, 0)
}

func (w *BaseWindowImpl) OnPaint() {
	// For performance, do not call h.HWND()
	w.defWndProc(w.hwnd, win32.WM_PAINT, 0, 0)
}

func (w *BaseWindowImpl) Destroy() error {
	return win32.DestroyWindow(w.HWND())
}

type MouseClickOpt win32.WPARAM

func (mk MouseClickOpt) Control() bool {
	return mk&win32.MK_CONTROL != 0
}

func (mk MouseClickOpt) LButton() bool {
	return mk&win32.MK_LBUTTON != 0
}

func (mk MouseClickOpt) MButton() bool {
	return mk&win32.MK_MBUTTON != 0
}

func (mk MouseClickOpt) RDown() bool {
	return mk&win32.MK_RBUTTON != 0
}

func (mk MouseClickOpt) Shift() bool {
	return mk&win32.MK_SHIFT != 0
}

func (mk MouseClickOpt) XButton1() bool {
	return mk&win32.MK_XBUTTON1 != 0
}

func (mk MouseClickOpt) XButton2() bool {
	return mk&win32.MK_XBUTTON2 != 0
}

func (w *BaseWindowImpl) WndProc(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM) win32.LRESULT {
	if w.msgListeners != nil {
		if listeners := w.msgListeners[message]; listeners != nil {
			for _, l := range listeners {
				l(hwnd, message, wParam, lParam)
			}
		}
	}
	switch message {
	case win32.WM_NCDESTROY:
		windowProp.Set(hwnd, nil)
		w.hwnd = 0
	case win32.WM_DESTROY:
		LookupWindow(hwnd).OnDestroy()
	case win32.WM_CTLCOLORSTATIC:
		if ret, err := win32.SendMessageW(win32.HWND(lParam), appmsg.REFLECT_CTLCOLORSTATIC, wParam, lParam); err == nil && ret != 0 {
			return ret
		}
	case win32.WM_LBUTTONUP:
		w.callOnLButtonUpListener(MouseClickOpt(wParam), int(win32.GET_X_LPARAM(lParam)), int(win32.GET_Y_LPARAM(lParam)))
	case win32.WM_LBUTTONDOWN:
		w.callOnLButtonDownListener(MouseClickOpt(wParam), int(win32.GET_X_LPARAM(lParam)), int(win32.GET_Y_LPARAM(lParam)))
	case win32.WM_RBUTTONUP:
		w.callOnRButtonUpListener(MouseClickOpt(wParam), int(win32.GET_X_LPARAM(lParam)), int(win32.GET_Y_LPARAM(lParam)))
	case win32.WM_RBUTTONDOWN:
		w.callOnRButtonDownListener(MouseClickOpt(wParam), int(win32.GET_X_LPARAM(lParam)), int(win32.GET_Y_LPARAM(lParam)))
	case win32.WM_PAINT:
		LookupWindow(hwnd).OnPaint()
		return 0 // Not calling default.
	case win32.WM_DPICHANGED:
		// For top level windows.
		suggested := (*win32.RECT)(unsafe.Pointer(uintptr(unsafe.Add(nil, lParam))))
		win32.SetWindowPos(hwnd, 0,
			win32.INT(suggested.Left), win32.INT(suggested.Top), win32.INT(suggested.Width()), win32.INT(suggested.Height()),
			win32.SWP_NOZORDER|win32.SWP_NOACTIVATE)
	}
	return w.defWndProc(hwnd, message, wParam, lParam)
}

func (w *BaseWindowImpl) defWndProc(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM) win32.LRESULT {
	return win32.CallWindowProcW(w.oldWndProc, hwnd, message, wParam, lParam)
}

// wndProc is the native window procedure for all windows created or attached by this package.
var wndProc = windows.NewCallback(func(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM) (result win32.LRESULT) {
	result = LookupWindow(hwnd).WndProc(hwnd, message, wParam, lParam)
	internal_app.CallMsgRetListeners(internal_app.ThreadLocalApp(), hwnd, message, wParam, lParam, result)
	return
})

type PopupMenuSpec struct {
	Flags   win32.TRACK_POPUP_MENU_FLAG
	X, Y    win32.LONG // Screen coordinates.
	Exclude *win32.RECT
}

// TrackPopupMenu tracks a popup menu.
// If spec is nil, default flag, empty exclude RECT and GetCursorPos() are used.
func (w *BaseWindowImpl) TrackPopupMenu(menu *menu.Menu, spec *PopupMenuSpec) error {
	var flags win32.TRACK_POPUP_MENU_FLAG
	var pt = &win32.POINT{}
	var params *win32.TPMPARAMS

	if spec != nil {
		// Notify message is needed.
		if spec.Flags&win32.TPM_NONOTIFY != 0 {
			return errors.New("invalid param: TPM_NONOTIFY is not allowed")
		}
		flags = spec.Flags
		pt.X = win32.LONG(spec.X)
		pt.Y = win32.LONG(spec.Y)
		if spec.Exclude != nil {
			params = &win32.TPMPARAMS{
				Size:    win32.UINT(unsafe.Sizeof(win32.TPMPARAMS{})),
				Exclude: *spec.Exclude,
			}
		}
	} else {
		var err error
		pt, err = win32.GetCursorPos()
		if err != nil {
			return err
		}
		flags = gg.If(win32.GetSystemMetrics(win32.SM_MENUDROPALIGNMENT) != 0, win32.TPM_RIGHTALIGN, win32.TPM_LEFTALIGN)
	}

	// In case the keyboard layout is changed since the menu is created.
	menu.OnKeyboardLayoutChange(win32.GetKeyboardLayout(0))

	// TPM_RIGHTBUTTON makes right clicking select the menu item.
	// If not set, right clicking(releasing right mouse button) of a menu item will post a WM_RBUTTONUP message to the window.
	// If win32.TrackPopupMenuEx is called in a WM_RBUTTONUP handler, the extra WM_RBUTTONUP message will cause a recursive call
	// to win32.TrackPopupMenuEx which results an error of "1446 Popup menu already active".
	flags |= win32.TPM_RIGHTBUTTON
	_, err := win32.TrackPopupMenuEx(menu.HMENU(), flags, win32.INT(pt.X), win32.INT(pt.Y), w.HWND(), params)
	return err
}

func (w *BaseWindowImpl) Show(cmd win32.SHOW_WINDOW_CMD) {
	win32.ShowWindow(w.HWND(), cmd)
}

func (w *BaseWindowImpl) SetText(text string) error {
	return win32util.SetWindowText(w.HWND(), text)
}

func (w *BaseWindowImpl) Text() (string, error) {
	return win32util.GetWindowText(w.HWND())
}

func (w *BaseWindowImpl) DPI() (win32.UINT, error) {
	return win32.GetDpiForWindow(w.HWND())
}

func (w *BaseWindowImpl) GetClientRect() (*win32.RECT, error) {
	var rect win32.RECT
	if err := win32.GetClientRect(w.HWND(), &rect); err != nil {
		return nil, err
	}
	return &rect, nil
}

func (w *BaseWindowImpl) GetWindowRect() (*win32.RECT, error) {
	var rect win32.RECT
	if err := win32.GetWindowRect(w.HWND(), &rect); err != nil {
		return nil, err
	}
	return &rect, nil
}

func (w *BaseWindowImpl) InvalidateRect(rect *win32.RECT, eraseBk bool) error {
	return win32.InvalidateRect(w.HWND(), rect, eraseBk)
}

func (w *BaseWindowImpl) AddMsgListener(message win32.UINT,
	listener func(hwnd win32.HWND, message win32.UINT, wParam win32.WPARAM, lParam win32.LPARAM)) MsgListenerKey {
	if listener == nil {
		panic("nil listener")
	}
	if w.msgListeners == nil {
		w.msgListeners = make(map[win32.UINT]msgListenerMap)
	}

	listeners := w.msgListeners[message]
	if listeners == nil {
		listeners = make(msgListenerMap)
		w.msgListeners[message] = listeners
	}
	key := MsgListenerKey{&listeners, new(uintptr)}
	listeners[key] = listener
	return key
}

func (w *BaseWindowImpl) Value(key any) any {
	if w.values == nil {
		return nil
	}
	return w.values[key]
}

func (w *BaseWindowImpl) SetValue(key, value any) {
	if value == nil {
		delete(w.values, key)
		return
	}
	if w.values == nil {
		w.values = make(map[any]any)
	}
	w.values[key] = value
}

// wiErrAlreadyAttached is returned by Attach if the HWND or *WindowBase
// is already attached.
var ErrAlreadyAttached = errors.New("window is already attached")

func Attach(hwnd win32.HWND, window BaseWindow) error {
	if LookupWindow(hwnd) != nil {
		return ErrAlreadyAttached
	}
	if proc, err := win32.GetWindowLongPtrW(hwnd, win32.GWLP_WNDPROC); err != nil {
		return err
	} else if proc == win32.LONG_PTR(wndProc) {
		return ErrAlreadyAttached
	}

	oldProc, err := win32.SetWindowLongPtrW(hwnd, win32.GWLP_WNDPROC, win32.LONG_PTR(wndProc))
	if err != nil {
		return err
	}
	windowProp.Set(hwnd, &window)
	window.setHWND(hwnd)
	window.setOldWndProc(uintptr(oldProc))
	return nil
}

// Init creates and initializes the window.
// The return value is the same as the window parameter.
// It panics if the window is already initialized or if creating or initializing the window fails.
// Only [BaseWindow] instances initialized by this function can be retrieved by [LookupWindow].
// One can wrap an uninitialized [BaseWindow] instance to crate a new window type, and then call this
// function to initialize the instance of the new type. See Wrapper example for details.
func Init[T BaseWindow](window T) T {
	if window.initialized() {
		panic("window is already initialized")
	}
	if err := Attach(window.CreateHandle(), window); err != nil {
		panic(err)
	}
	window.OnInit()
	return window
}
